### PR TITLE
Support calls fetch(destination, env) and run(env)

### PR DESCRIPTION
**Pull request by lukaszachy**
Related to https://github.com/psss/tmt/issues/530#issuecomment-775781414

### CODE REVIEW

**Comment by lukaszachy** [comment]
Hm, we will need 'env' as well, necessary to be used as https://github.com/psss/tmt/blob/3e4673b5955166f880c19608a3bdf902661bbf01/tmt/beakerlib.py#L129

**Comment by psss** [comment]
Hooray, everything's green! :)

**Pull request merged**
