### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by psss**
Remove related stuff from the spec file.
Remove Python 2 only code, disable epel-7 packit.
Remove irrelevant adjust rule from unit tests.
Get rid of other `unicode` related leftovers.
Use default encoding for running commands.
Explicitly mention the `utf-8` encoding in the docs.
Remove unnecessary `object` from class definitions.

### CODE REVIEW

**Comment by psss** [comment]
@lachmanfrantisek, I've removed `epel-7` from the `.packit.yaml` but the `epel-7` build seems to be included in the latest packit [job](https://copr.fedorainfracloud.org/coprs/packit/psss-fmf-144/build/2917945/). Is that expected?

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek, I've removed epel-7 from the .packit.yaml but the epel-7 build seems to be included in the latest packit job. Is that expected?

I thought we had already fixed this. (@mfocko I recall we've discussed this).

@psss It should affect only this PR and will not be used once merged...

**Comment by mfocko** [comment]
@psss It's twice there, once for `pull_request` trigger and second time for builds _on push to `master`_ (← this one I see removed in diff for PR).

We've also changed the behavior, such that we remove targets only on projects **created and maintained** by Packit user, so if you want to remove `epel-7` from the Copr repo you own (where you build everything pushed to `master`), you need to do so yourself. However it shouldn't build for it, cause it checks only if the targets from config are enabled and builds those. I won't mind if you check it ;)

**Comment by psss** [comment]
@lachmanfrantisek, @mfocko, thanks for quick review and hints. I've completely forgotten that the target config is there twice. After removing the second one everything seems to be working as expected. Sorry for the noise.

**Review by lukaszachy — CHANGES_REQUESTED** [review]
I think we can remove also `adjust` part of `tests/unit/main.fmf` as there is no way python2 tests will pass

**Review by jscotka — COMMENTED** [review]
fixes seems more well,  but not sure if there are some missing fixes inside rest of the code. e.g.some `unicode(item)` notations inside utils e.g. on line  https://github.com/psss/fm/blob/master/fmf/utils.py#L316 what seems related to Python 2 I think. But maybe it is not hamffull and should not cause anything important.

**Comment by lukaszachy** [comment]
Good point @jscotka , `unicode(item)` raises `NameError:` for python3 so except cause will be hit each time

**Comment by psss** [comment]
@lukaszachy, @jscotka, good points! All should be covered now.

**Review by jscotka — APPROVED** [review]
Now, I'm fine with changes. after removing old `unicode()` stuff

**Comment by psss** [comment]
> I think that also "class Tree(object)" should not be used inside python3 just "class Tree:"

@jscotka could you please elaborate a bit more why `object` should not be used?

**Comment by jscotka** [comment]
> > I think that also "class Tree(object)" should not be used inside python3 just "class Tree:"
> 
> @jscotka could you please elaborate a bit more why `object` should not be used?

I had that feeling, maybe there were some hints or docs what I've read that somewhere, now when looking inside: https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object it seems that there were difference inside Python2, and in python3 there syntax `class X:` and `class X(object):` is totally equivalent, so that reason why to not use it is that you saves 8 chars.

**Comment by psss** [comment]
@jscotka, thanks for clarification. Unnecessary `object` strings removed from class definitions. @lukaszachy anything else to change or are we ready for squash and merge?

**Review by lukaszachy — APPROVED** [review]

**Comment by lukaszachy** [comment]
LGTM.

**Review by jscotka — APPROVED** [review]
LGTM

**Review by FrNecas — APPROVED** [review]
The code's a lot cleaner now, I like it!

**Comment by psss** [comment]
@lukaszachy, @jscotka, @FrNecas, thanks much for the review! Rebased, squashed, now waiting for tests.

**Pull request merged**
