### PR TITLE
 Initial set of stories, tests and testsets 

### PR DESCRIPTION
**Pull request by psss**

### CODE REVIEW

**Comment by psss** [comment]
@thrix, any idea why tests haven't been run?

**Comment by thrix** [comment]
@psss let me check the scheduler ... I need to show you how to debug this @psss :)

**Comment by thrix** [comment]
@psss please rebase so testing is enabled :) 

https://github.com/psss/fmf/blob/2a889fca49639115c100e09b91a259d2cd973355/.packit.yaml

Testing is not configured :)

**Comment by psss** [comment]
Oh! I'm blind. Wrong branch. I see. Thanks, @thrix!

**Comment by thrix** [comment]
@psss the error from testing farm was not forwarded: https://github.com/packit-service/packit-service/issues/145

The issues seems to be that rawhide image is broken ... need to confirm ...

**Comment by thrix** [comment]
confirmed, rawhide cannot be booted. We will need to qualify the images before using them :(

**Comment by thrix** [comment]
I have a workaround which will used only qualified fedora rawhide images from:
https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-rawhide-image-test/

For now this is fine ... fix on the way

**Comment by thrix** [comment]
@psss please /packit copr-rebuild :)

https://quay.io/repository/testing-farm/cruncher/build/7c940d82-7289-45b0-adb9-66f027416fb8

**Comment by thrix** [comment]
Noting that old results are not cleared: https://github.com/packit-service/packit-service/issues/140

**Pull request merged**
