### PR TITLE
introduce new automated key in metadata - metadata file location

### PR DESCRIPTION
**Pull request by jscotka**
* very good for debugging
example output od command ``$ fmf examples``:
```
examples/merge/parent/child
description: General descriptionSpecific description
fmf_config: examples/merge/parent.fmf
tags: Tier1 and Tier2
time: 15
examples/code
examples/wget/download/test
description: Check basic download options
fmf_config: examples/wget/download/main.fmf
tags: Tier1 and TierSecurity
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 3 min
examples/wget/download/requirements/no-clobber
coverage: wget/download
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/server-response
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/output-document
coverage: wget/download
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/quota
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/bind-address
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/spider
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/tries
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/continue
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/timestamping
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/get-file
coverage: wget/download
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/download/requirements/progress
fmf_config: examples/wget/download/main.fmf
priority: low
requirement: Various download options working correctly
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/recursion/fast
depth: 10
description: Check recursive download options
fmf_config: examples/wget/recursion/fast.fmf
tags: Tier2
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 1 min
examples/wget/recursion/deep
depth: 1000
description: Check recursive download options
fmf_config: examples/wget/recursion/deep.fmf
tags: Tier2
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 10 min
examples/wget/requirements/download/output-document-file
coverage: wget/download
fmf_config: examples/wget/requirements/main.fmf
priority: medium
requirement: Save content to a file.
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/download/output-document-pipe
coverage: wget/download
fmf_config: examples/wget/requirements/main.fmf
priority: medium
requirement: Save content to pipe.
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/upload/post-file
coverage: wget/protocols/http
fmf_config: examples/wget/requirements/main.fmf
priority: medium
requirement: Upload a file to the server
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/upload/post-data
coverage: wget/protocols/http
fmf_config: examples/wget/requirements/main.fmf
priority: medium
requirement: Upload a string to the server
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/protocols/ftp
coverage: wget/protocols/ftp
fmf_config: examples/wget/requirements/main.fmf
priority: high
requirement: Download a file using the ftp protocol.
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/protocols/http
coverage: wget/protocols/http
fmf_config: examples/wget/requirements/main.fmf
priority: high
requirement: Download a file using the http protocol.
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/requirements/protocols/https
coverage: wget/protocols/https
fmf_config: examples/wget/requirements/main.fmf
priority: high
requirement: Download a file using the https protocol.
tester: Petr Šplíchal <psplicha@redhat.com>
examples/wget/protocols/ftp
description: Test file download using the ftp protocol.
details: This is a very long and detailed description of what the wget/protocols/ftp test actually does including multiple examples and information about proper environment setup.
fmf_config: examples/wget/protocols/ftp/main.fmf
tags: Tier1
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 1 min
examples/wget/protocols/http
description: Test file download using the http protocol.
details: This is a very long and detailed description of what the wget/protocols/http test actually does including multiple examples and information about proper environment setup.
fmf_config: examples/wget/protocols/http/main.fmf
tags: Tier1
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 1 min
examples/wget/protocols/https
description: Test file download using the https protocol.
details: This is a very long and detailed description of what the wget/protocols/https test actually does including multiple examples and information about proper environment setup.
fmf_config: examples/wget/protocols/https/main.fmf
tags: Tier1
test: runtest.sh
tester: Petr Šplíchal <psplicha@redhat.com>
time: 1 min
```

### CODE REVIEW

**Comment by psss** [comment]
Thanks for the idea. I'm not quite sure about it: Which "metadata file location" is this new key supposed to contain? The thing is that an object can be defined at several places. See:

* http://fmf.readthedocs.io/en/latest/features.html#scatter

Here's an example:

    > tree
    .
    ├── main.fmf
    └── something
        └── main.fmf
    
    
    > cat main.fmf 
    /something:
        tester: me
        value: 3
    > cat something/main.fmf 
    value: 5
    > fmf
    ha/something
    fmf_config: ./something/main.fmf
    tester: me
    value: 5


Also I don't think it would be good to have this item included in the output by default. Perhaps only when `--debug` is enabled?

**Comment by jscotka** [comment]
Hi,
sure, object can be defined on several place. But at least this latest file is good starting point to inspect it. otherwise, it is easy to list all of them, because you know that there is tree structure, so that
use ``fmf --whole`` does that, and you can check all files in parent tree.

I think it should be part of default output, or there could be introduced new command line option, to enable it like (``--insert-config-path``).
because there are several usecases:
 * debugging test metadata (in this case part of ``--debug`` could be enough)
 * using this as another relative path location for tests. FMF should be flexible enough to allow also use this file path location as path to test. because it could be common case, to have tests with these files.
like ``main.fmf``
```
/test1
  test: unit1.py
/test2
  test2: unit2.py
```
as we've discussed it could be also solved via special key, eg. ``path`` but this is good enough too, because fmf config file is real file path location, and FMF should provide this path.

and then with second PR:
https://github.com/psss/fmf/pull/16
it could be used like: ``fmf-output --key test --formatstring '{}/{}' --value 'dirname(data[fmf_config])' --value 'data[test]'``

This will allow very elegant way instead of using explicit ``path`` key, also for virtual test. and relatively easy to understand how to deal with them.

**Comment by jscotka** [comment]
### recent output, and command line support
 * command ``fmf  --key test examples/wget/``
```
wget/download/test
description: 'Check basic download options'
tags: ['Tier1', 'TierSecurity']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '3 min'
wget/recursion/fast
depth: 10
description: 'Check recursive download options'
tags: ['Tier2']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/recursion/deep
depth: 1000
description: 'Check recursive download options'
tags: ['Tier2']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '10 min'
wget/protocols/ftp
description: 'Test file download using the ftp protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/ftp test actually does including multiple examples and information about proper environment setup.'
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/protocols/http
description: 'Test file download using the http protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/http test actually does including multiple examples and information about proper environment setup.'
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/protocols/https
description: 'Test file download using the https protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/https test actually does including multiple examples and information about proper environment setup.'
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
```

 * command: ``fmf  --key test examples/wget/ --config_paths``
```
wget/download/test
description: 'Check basic download options'
fmf_config: examples/wget/download/main.fmf
tags: ['Tier1', 'TierSecurity']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '3 min'
wget/recursion/fast
depth: 10
description: 'Check recursive download options'
fmf_config: examples/wget/recursion/fast.fmf
tags: ['Tier2']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/recursion/deep
depth: 1000
description: 'Check recursive download options'
fmf_config: examples/wget/recursion/deep.fmf
tags: ['Tier2']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '10 min'
wget/protocols/ftp
description: 'Test file download using the ftp protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/ftp test actually does including multiple examples and information about proper environment setup.'
fmf_config: examples/wget/protocols/ftp/main.fmf
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/protocols/http
description: 'Test file download using the http protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/http test actually does including multiple examples and information about proper environment setup.'
fmf_config: examples/wget/protocols/http/main.fmf
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
wget/protocols/https
description: 'Test file download using the https protocol.'
details: 'This is a very long and detailed description of what the wget/protocols/https test actually does including multiple examples and information about proper environment setup.'
fmf_config: examples/wget/protocols/https/main.fmf
tags: ['Tier1']
test: 'runtest.sh'
tester: Petr Šplíchal <psplicha@redhat.com>
time: '1 min'
```

**Comment by jscotka** [comment]
@AloisMahdal this feature is already part of upstream and used ``{}`` and ``.format()`` method.

**Comment by jscotka** [comment]
@psss I wanted to add there all configs files what was used for loading, but there are two issues:
 1. loading of scatter files is mismatched, so that loading of files is bad: https://github.com/psss/fmf/issues/18
 2. I'm unable to find place where to put this code. I'm little bit confused, how to do it in the best way. I thought that just replace this code in ``update`` method by appending to list instead of just string assign.
 
Maybe both issues are the same, and solving of 1st issue solves also second one, because it simplify the place where to put this code.

**Comment by psss** [comment]
Deeper virtual hierarchy should be fixed and I've introduced a new attribute `sources` as a list of metadata files used to build the metadata tree. The list of source files is showed when run in debug mode:

    > fmf --name recursion examples/wget --debug

    wget/recursion/fast
    depth: 10
    description: 'Check recursive download options'
    tags: ['Tier2']
    test: 'runtest.sh'
    tester: Petr Šplíchal <psplicha@redhat.com>
    time: '1 min'
    Sources:
    /home/psss/git/fmf/examples/wget/main.fmf
    /home/psss/git/fmf/examples/wget/recursion/main.fmf
    /home/psss/git/fmf/examples/wget/recursion/fast.fmf

    wget/recursion/deep
    depth: 1000
    description: 'Check recursive download options'
    tags: ['Tier2']
    test: 'runtest.sh'
    tester: Petr Šplíchal <psplicha@redhat.com>
    time: '10 min'
    Sources:
    /home/psss/git/fmf/examples/wget/main.fmf
    /home/psss/git/fmf/examples/wget/recursion/main.fmf
    /home/psss/git/fmf/examples/wget/recursion/deep.fmf

I believe this should cover your use case. Is that right, Honzo?

**Comment by jscotka** [comment]
Hi, @psss yes, this suits my cases, just I don't like idea that it is shown just with --debug option, but it is better than nothing :-)

**Comment by psss** [comment]
Would `--verbose` or special option `--sources` be better? I don't think it
makes sense in the default output.

**Comment by jscotka** [comment]
@psss finally https://github.com/psss/fmf/pull/23 would be the best.

this just seems like Sources: .... is part of metadata tree with ``--debug`` option, but this is just printed out as string. So actual solution is little bit tricky from my PoV,

**Pull request closed without merging**
