### PR TITLE
Remove the duplicate build job from packit config

### PR DESCRIPTION
**Pull request by psss**

### CODE REVIEW

**Comment by psss** [comment]
@lachmanfrantisek, no update from packit if the extra section is removed.

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek, no update from packit if the extra section is removed.

But it works well without that change, isn't it?

**Comment by psss** [comment]
@lachmanfrantisek, yes, but then you get two results for each distro which might be confusing.

**Comment by lachmanfrantisek** [comment]
@psss Yes, I just wanted to make sure that it (somehow) works until we fix it.

**Comment by psss** [comment]
I see. Thanks for looking into this, @lachmanfrantisek.

**Pull request merged**
