### PR TITLE
Prevent exploring tests in the tmt directory

### PR DESCRIPTION
**Pull request by psss**
Also checking that the context adjust works as expected.

### CODE REVIEW

**Comment by psss** [comment]
@lukaszachy, @thrix, fyi: Testing the context adjust support in Packit here.

**Comment by TomasTomecek** [comment]
All tests passed - does it work as expected? :O

**Comment by psss** [comment]
Works nicely! Except for one detail: Could you provide `distro` value `centos-8` instead of `epel-8`? We need to use the same naming for context dimension across all tools as defined by the [specification](https://tmt.readthedocs.io/en/latest/spec/context.html#dimension).

**Comment by psss** [comment]
The epel/centos issue should be fixed by https://github.com/packit/packit-service/pull/1012.

**Comment by thrix** [comment]
@psss can you please remove here staging packit app pls?

**Comment by psss** [comment]
I just temporarily enabled them to verify the context adjust support works as expected. See the pull request linked above.

**Comment by thrix** [comment]
@psss sorry missed this important detail :)

**Comment by psss** [comment]
The epel/centos mapping now [works](http://artifacts.dev.testing-farm.io/317c3b83-246e-4727-8fd0-48ee9092491f/work-featuresidl0GP/log.txt) as expected.

**Pull request merged**
