### PR TITLE
Enable beakerlib smoke test in the testing farm

### PR DESCRIPTION
**Pull request by psss**

### CODE REVIEW

**Comment by thrix** [comment]
@psss you need to hit this by yourself :)

**Comment by thrix** [comment]
@psss so now it fails :) that is good :)

**Comment by thrix** [comment]
Issue in cruncher:
https://gitlab.com/testing-farm/cruncher/issues/1

**Comment by thrix** [comment]
hmm, interesting that the packit rebuild did not get initiated

**Comment by psss** [comment]
Sometimes it takes a little bit longer... I'll give it a few minutes.

**Comment by thrix** [comment]
@psss seems ome packit problem :( try to retrigger

**Comment by thrix** [comment]
weeeee
@psss success success!!!

**Comment by psss** [comment]
Hoooray! :-)

**Pull request merged**
