### PR TITLE
Use a deep copy when storing raw node data

### PR DESCRIPTION
**Pull request by psss**
When the `adjust()` method is used it can modify data referenced
from the raw data dictionaries. Make a deep copy to ensure the
original data are preserved.

- [ ] add test coverage

### CODE REVIEW

**Review by jscotka — APPROVED** [review]
Hi, seems well.
I've also met this issue, but though that issue is on my side with regerated data from python decorators.
yep, seems like `adjust()` causes it. BTW, would not be better to fix adjust method if it somehow modify something what it should not modify? e.g. there can be found another issue with method use parameter and reference and potential future problem. and also reason why I've added lines for adjust to test https://github.com/psss/fmf/blob/master/tests/unit/test_modify.py#L82 :-) to prove that it does not modify adjust rule.

**Comment by lukaszachy** [comment]
I believe it would be better to allow repetitive `adjust`  calls - tmt object stays "adjusted" until next adjust call. 
AFAIK Alex and I need to remember tmt state before adjust (`copy` method)  as our tooling need to call adjust multiple times.

**Comment by jscotka** [comment]
my feeling is that it should be keep. I can imagine that in pipeline some additional step may change adjust output, e.g. some artificial example :-) I can have centOS and will use RH tool for converting centos to RHEL, and then adjust have to match that it is not centos but rhel (e.g. in `prepare` phase). I understand that it is little bit artificial, but way, that multiple call of adjustment is not bad. but feature. from py PoV

**Comment by psss** [comment]
Makes sense. Let's allow repeated `adjust()` calls then. Will update the code.

**Comment by jscotka** [comment]
@psss @lukaszachy maybe as quick fix we can also use this patch and create new one (or issue) for your mentioned solution. Because it will be then also feature not just bugfix.

**Review by lukaszachy — APPROVED** [review]
I've added test, @psss please review.

**Comment by psss** [comment]
Thanks, @lukaszachy. The test looks good. Added changes needed to keep the original adjust rules intact, including a simple test.

**Comment by lukaszachy** [comment]
Hm, so integration fails on f34 as tmt changed `'enabled\s+yes'` to `true`

**Comment by psss** [comment]
Yeap, another motivation to find an elegant solution for psss/tmt/issues/585 as soon as possible.

**Pull request merged**
